### ISSUE TITLE
cuttlebelle.com started the fans on my MBP

### ISSUE THREAD

**Issue by alexei** [cuttlebelle/website#1]
Steps to reproduce:

1. Open Safari
2. Go to https://cuttlebelle.com
3. Wait a couple of minutes

**Comment by dominikwilkowski** [comment]
Hah fair enough. I am using some css animations for the banner on the top to have it still look pretty when js is off. I might revisit that :)
Thanks for reporting.

**Comment by dominikwilkowski** [comment]
I haven't seen any issues since this was reported so I'll close it for now. Feel free to reopen.
