### ISSUE TITLE
I do not want to scroll down on the homepage to use the navigation

### ISSUE THREAD

**Issue by alex-page** [cuttlebelle/website#9]
When I go to the cuttlebelle site 99% of the time I am reading the docs. I arrive at the home page and am always frustrated that I have to scroll down and then up again to see the navigation.

I am happy to do a PR to change this functionality let me know if you think this is a good idea 👍

**Comment by dominikwilkowski** [comment]
Yeah I heard that before... Need to think about this :)

**Comment by dominikwilkowski** [comment]
I just did it the simplest way I could think of :)

**Comment by alex-page** [comment]
Legend thanks mate!!!!
